# Run after Administrator on windows or you get error with mounting volums
version: '3.7'

services:

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      PGDATA: /tmp
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 15432:5432

  adminer:
    container_name: postgres_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080